// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var initialState = /* record */[
  /* expression */"",
  /* result */9.0
];

function toString(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              return React.createElement("div", {
                          className: "calculator"
                        }, React.createElement("div", {
                              className: "expression"
                            }, React.createElement("p", undefined, state[/* expression */0]), React.createElement("div", {
                                  className: "result"
                                }, React.createElement("p", undefined, Pervasives.string_of_float(state[/* result */1])))), React.createElement("button", {
                              className: "ac",
                              onClick: (function () {
                                  return Curry._1(send, "");
                                })
                            }, "AC"), React.createElement("button", {
                              className: "divide",
                              onClick: (function () {
                                  return Curry._1(send, "/");
                                })
                            }, "/"), React.createElement("button", {
                              className: "multiply",
                              onClick: (function () {
                                  return Curry._1(send, "x");
                                })
                            }, "X"), React.createElement("button", {
                              className: "subtract",
                              onClick: (function () {
                                  return Curry._1(send, "-");
                                })
                            }, "-"), React.createElement("button", {
                              className: "add",
                              onClick: (function () {
                                  return Curry._1(send, "+");
                                })
                            }, "+"), React.createElement("button", {
                              className: "equals",
                              onClick: (function () {
                                  return Curry._1(send, "");
                                })
                            }, "="), React.createElement("button", {
                              className: "dot",
                              onClick: (function () {
                                  return Curry._1(send, ".");
                                })
                            }, "."), React.createElement("button", {
                              className: "zero",
                              onClick: (function () {
                                  return Curry._1(send, "0");
                                })
                            }, "0"), React.createElement("button", {
                              className: "one",
                              onClick: (function () {
                                  return Curry._1(send, "1");
                                })
                            }, "1"), React.createElement("button", {
                              className: "two",
                              onClick: (function () {
                                  return Curry._1(send, "2");
                                })
                            }, "2"), React.createElement("button", {
                              className: "three",
                              onClick: (function () {
                                  return Curry._1(send, "3");
                                })
                            }, "3"), React.createElement("button", {
                              className: "four",
                              onClick: (function () {
                                  return Curry._1(send, "4");
                                })
                            }, "4"), React.createElement("button", {
                              className: "five",
                              onClick: (function () {
                                  return Curry._1(send, "5");
                                })
                            }, "5"), React.createElement("button", {
                              className: "six",
                              onClick: (function () {
                                  return Curry._1(send, "6");
                                })
                            }, "6"), React.createElement("button", {
                              className: "seven",
                              onClick: (function () {
                                  return Curry._1(send, "7");
                                })
                            }, "7"), React.createElement("button", {
                              className: "eight",
                              onClick: (function () {
                                  return Curry._1(send, "8");
                                })
                            }, "8"), React.createElement("button", {
                              className: "nine",
                              onClick: (function () {
                                  return Curry._1(send, "9");
                                })
                            }, "9"));
            }),
          /* initialState */(function () {
              return initialState;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[
                          /* expression */state[/* expression */0] + action,
                          /* result */state[/* result */1]
                        ]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.initialState = initialState;
exports.toString = toString;
exports.component = component;
exports.make = make;
/* component Not a pure module */
